package com.java.SpringBootJDBC;

import java.util.List;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ConfigurableApplicationContext;
import org.springframework.context.annotation.ComponentScan;

import com.java.Dao.EmployeesDAOImpl;
import com.java.Model.Employees;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
@ComponentScan(basePackages = "com.java.Dao")
public class SpringBootJdbcApplication {

	public static void main(String[] args) {
		ConfigurableApplicationContext container =SpringApplication.run(SpringBootJdbcApplication.class, args);
		EmployeesDAOImpl dao=container.getBean(EmployeesDAOImpl.class);
		
		List<Employees> list=dao.getEmployeesInfo();
		for(Employees ls:list)
		{
			System.out.println(ls);
		}
	}

}
