package com.java.SpringDataJpa;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.domain.EntityScan;
import org.springframework.context.ConfigurableApplicationContext;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;

import com.java.SpringDataJpa.Entity.Library;
import com.java.SpringDataJpa.Service.LibraryServices;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
public class SpringDataJpaApplication {

	public static void main(String[] args) {
		ConfigurableApplicationContext container=SpringApplication.run(SpringDataJpaApplication.class, args);
		 
		LibraryServices lib=container.getBean(LibraryServices.class);
		
		lib.fetchBybookName("DataStructur").forEach(v->System.out.println(v));
		//lib.fetchBybookName("HarryPorter", "Gate").forEach(v->System.out.println(v));
		
		System.out.println("Use OF Between");
		//lib.searchByboolPrice(232.98,34221.98).forEach(v->System.out.println(v));
		
		System.out.println("Updating the price");
		//lib.updateboolPriceBybookPublisher(3234.32, "ABCPublisher");
		
		System.out.println("Deleting the price");
		//lib.deleteBoolPriceByboolPrice(34243.98);
		System.out.println("Adding New Items In Library");
		//lib.insertBookInfo(44,"Chemisty", "DineshPublisher", 2321.32);
		System.out.println("Fetching system Date and Time");
		System.out.println(lib.fetchTheSystemDateAndTime());
		
	}

}
