package com.java.SpringBoot01;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.ConfigurableApplicationContext;

import com.java.SpringBoot01.Services.TestingClass;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
public class SpringBoot01Application {

	public static void main(String[] args)
	{
		ConfigurableApplicationContext container=SpringApplication.run(SpringBoot01Application.class, args);
		TestingClass test=container.getBean(TestingClass.class);
		test.checkMessage();
		container.close();
	}

}
