package com.java.SpringDataJpa;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.autoconfigure.domain.EntityScan;
import org.springframework.context.ConfigurableApplicationContext;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;

import com.java.SpringDataJpa.Entity.Library;
import com.java.SpringDataJpa.Service.LibraryServices;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
public class SpringDataJpaApplication {

	public static void main(String[] args) {
		ConfigurableApplicationContext container=SpringApplication.run(SpringDataJpaApplication.class, args);
		 
		LibraryServices lib=container.getBean(LibraryServices.class);
		lib.fetchByCost(34243.41).forEach(v->System.out.println(v.getBookName()));;	
	}

}
